# Dependabot will run on day 20 of each month at 03:26 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    schedule:
      interval: 'cron'
      cronjob: '7 3 * * 3'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    assignees:
      - 'iobroker-community-adapters'
    versioning-strategy: 'increase'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    directories:
      - '**/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '47 5 * * 6'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    assignees:
      - 'iobroker-community-adapters'
